name: barcode_hid_listener
description: A headless, zero-dependency Flutter package for intercepting, buffering, and validating physical HID barcode scanner keystrokes (USB/Bluetooth).
version: 1.0.1
repository: https://github.com/AndresMontaniv/flutter_barcode_hid_listener
issue_tracker: https://github.com/AndresMontaniv/flutter_barcode_hid_listener/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
